name: freenom

on:
  schedule:
    - cron: '16 3 */1 * *'

  workflow_dispatch:
  
jobs:
  repo-sync:
    if: ${{ github.repository != 'luolongfei/freenom.git' }}

    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/luolongfei/freenom.git"
          source_branch: "main"
          destination_branch: "freenom"
          sync_tags: "true"
          github_token: ${{ secrets.PAT }}
