name: proxy-heroku

on:
  schedule:
    - cron: '15 3 */1 * *'

  workflow_dispatch:
  
jobs:
  repo-sync:
    if: ${{ github.repository != 'jygjgyu786k/hgfhgv456.git' }}

    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/jygjgyu786k/hgfhgv456.git"
          source_branch: "main"
          destination_branch: "proxy-heroku"
          sync_tags: "true"
          github_token: ${{ secrets.PAT }}
