name: proxy-heroku
on:
  schedule:
    - cron: '15 3 */1 * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-proxy-heroku-GithubSync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync proxy-heroku-GithubSync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/jygjgyu786k/hgfhgv456.git"
          source_branch: "main"
          destination_branch: "proxy-heroku"
          github_token: ${{ secrets.PAT }}
