name: v2ray-heroku-Vmess

on:
  schedule:
    - cron: '13 3 */1 * *'

  workflow_dispatch:
  
jobs:
  repo-sync:
    if: ${{ github.repository != 'bclswl0827/v2ray-heroku.git' }}

    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/bclswl0827/v2ray-heroku.git"
          source_branch: "master"
          destination_branch: "v2ray-heroku-Vmess"
          sync_tags: "true"
          github_token: ${{ secrets.PAT }}
