name: 青龙

on:
  schedule:
    - cron: '11 3 */1 * *'

  workflow_dispatch:
  
jobs:
  repo-sync:
    if: ${{ github.repository != 'whyour/qinglong.git' }}

    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/whyour/qinglong.git"
          source_branch: "develop"
          destination_branch: "qinglong"
          sync_tags: "true"
          github_token: ${{ secrets.PAT }}
