name: 青龙
on:
  schedule:
    - cron: '11 3 */1 * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-qinglong-GithubSync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync qinglong-GithubSync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/whyour/qinglong.git"
          source_branch: "develop"
          destination_branch: "qinglong"
          github_token: ${{ secrets.PAT }}
